import { jsPDF } from 'jspdf';

export interface ReportData {
    title: string;
    date: string;
    accessionNumber: string;
    findings: string;
    measurements: string;
    conclusion: string;
    screenshotDataUrl?: string;
    logoDataUrl?: string;
}

// Helper to load image as base64
async function loadImageAsDataUrl(src: string): Promise<string> {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            ctx?.drawImage(img, 0, 0);
            resolve(canvas.toDataURL('image/png'));
        };
        img.onerror = reject;
        img.src = src;
    });
}

export async function generateReportPDF(report: ReportData): Promise<Blob> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Try to add logo at top left
    try {
        const logoDataUrl = report.logoDataUrl || await loadImageAsDataUrl('/rology.png');
        doc.addImage(logoDataUrl, 'PNG', 15, 10, 30, 10);
    } catch (e) {
        console.warn('Could not load logo:', e);
    }

    // Header - Title centered but shifted down to accommodate logo
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(report.title, pageWidth / 2, y, { align: 'center' });
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${report.date}  |  Acc: ${report.accessionNumber}`, pageWidth / 2, y, { align: 'center' });
    y += 15;

    // Screenshot if available
    if (report.screenshotDataUrl) {
        try {
            const imgProps = doc.getImageProperties(report.screenshotDataUrl);
            const imgWidth = 160;
            const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
            const imgX = (pageWidth - imgWidth) / 2;

            doc.addImage(report.screenshotDataUrl, 'PNG', imgX, y, imgWidth, imgHeight);
            y += imgHeight + 15;
        } catch (error) {
            console.warn('Could not add screenshot to PDF:', error);
            y += 5;
        }
    }

    // Findings
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('FINDINGS', 20, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const findingsLines = doc.splitTextToSize(report.findings, pageWidth - 40);
    doc.text(findingsLines, 20, y);
    y += findingsLines.length * 5 + 10;

    // Measurements
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('MEASUREMENTS', 20, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const measurementLines = doc.splitTextToSize(report.measurements, pageWidth - 40);
    doc.text(measurementLines, 20, y);
    y += measurementLines.length * 5 + 10;

    // Conclusion
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('CONCLUSION', 20, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const conclusionLines = doc.splitTextToSize(report.conclusion, pageWidth - 40);
    doc.text(conclusionLines, 20, y);
    y += conclusionLines.length * 5 + 15;

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Electronically signed and generated by Rology Live', pageWidth / 2, 285, { align: 'center' });

    return doc.output('blob');
}

export function downloadPDF(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
